baseurl = "https://mcserverhosting.net/"
languageCode = "en-us"
title = "MC Server"
theme = "mc-server-theme-amp"
enableRobotsTXT = true

[params]
  title = 'MC Server Hosting LLC'
  description = "High performance hosting for your Minecraft, Web, VPS and Database."

  amp = true
  ampElements = [
    "amp-sidebar",
    "amp-script",
    "amp-selector",
    "amp-bodymovin-animation",
  ]

  themeColor = "#ff1d55"

  #adsensePublisher = "ca-pub-123456789"
  googleAnalytics = "UA-24240017-2"
  #appleItunesApp = "app-id=123456789, app-argument=app-name://link/to/app-content"
  ampManifest = "/amp-manifest.json"

  alternatePageName = "MC Server"
  organizationLogo = "https://gohugo-amp.gohugohq.com/logo.png"
  organizationName = "gohugohq.com"
  organizationAddress = "Some Street 123, 12345 City"
  publisherName = "gohugohq.com"
  publisherLogo = "https://gohugo-amp.gohugohq.com/logo-publisher.png" # https://developers.google.com/search/docs/data-types/articles#logo-guidelines
  publisherLogoWidth = 600
  publisherLogoHeight = 60

  stylesheetRegular = ["/base-styling.css"] # these styles are used when amp is disabled for a specific page
  javascriptRegular = ["/script.js"] # these scripts are used when amp is disabled for a specific page

  snipcartApiKey = "MDZiMGU5YTAtM2FlZS00ZDk5LTg0MTUtZDEwOWZkZWYwMWVkNjM3NTk2MTg2MzcwMTAxODE5"

  disableExitModal = true
  exitPopupTitle = "Before you go..."
  exitPopupText = "Save up to 50% Off your first month when you use your code today."
  exitPopupCode = "AUTO GEN"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  faq = 'faqs'

[markup]
  [markup.highlight]
    style = 'dracula'
