baseURL = "https://www.example.com/"
theme = "hugo-base-theme"
languageCode = "en-us"

title = "New Hugo Site"

[params]
  title = "My cool site"
  description = "Text about my cool site"
  images = ["site-feature-image.jpg"]

[taxonomies]
  series = "series"

[menu]
  [[menu.main]]
    name = "About Hugo"
    url = "/about/"
    weight = 100

  [[menu.main]]
    name = "Getting Started"
    url = "/getting-started/"
    weight = 200

  [[menu.main]]
    name = "Hello World"
    url = "/hello-world/"
    parent = "getting-started"
    weight = 210
